console.log("Valores verdadeiros...")
console.log(!!3)
console.log(!!-3)
console.log(!!" ")
console.log(!!"verdadeiro")
console.log(!!(ativo = true))
console.log(!!Infinity)
console.log(!![])
console.log(!!{})

console.log("Valores falsos...")
console.log(!!0)
console.log(!!NaN)
console.log(!!null)
console.log(!!(ativo = false))
console.log(!!undefined)

console.log("Pra finalizar...")
console.log("" || 0 || null || "Gustavo")